#!/bin/sh
#PBS -N gmrt_cnn
#PBS -l nodes=1:ppn=8:compute,walltime=12:00:00
#PBS -q small
# usmall is 32 items on the queue usmall2 is 8
#PBS -j oe

cd /home/kevin/rfi_ml/src

source ~/anaconda2/bin/activate rfi_ml

date

# python train_gmrt_cnn.py --num-processes 12 --save gmrt_cnn.model.saved
python -m cProfile -o train_gmrt_cnn.prof train_gmrt_cnn.py --num-processes 12 --save gmrt_cnn.model.saved

date
